# Generated by Django 2.2.6 on 2019-10-26 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191026_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField(verbose_name='Data do emprestimo')),
                ('data_devolucao', models.DateField(verbose_name='Data da devolução')),
                ('amigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Amigo')),
                ('revista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Revista')),
            ],
            options={
                'verbose_name': 'empréstimo',
                'verbose_name_plural': 'empréstimos',
            },
        ),
    ]
